### ISSUE TITLE
Website delay because of mmenu, all versions after 2.1.1

### ISSUE THREAD

**Issue by Cleanerrr** [dklemmt/contao_dk_mmenu#47] opened 2020-02-25 10:31 UTC
Hi,
I'm using mmenu in my many Contao projects, but with last versions have some problems.
The problem is with web site loading. When we open web site just for one sec we can see all mmenu items list on the left side. This list pushes all web site down and after one or two-second everything is OK. I supposed that the problem can be some conflict with Rocksolid slider plugin. On the websites where I don't have Rosckolid slider, the problematic delay is shorter.
This is not a problem with version 2.1.1, but every after it.

**Comment by fritzmg** [comment] 2020-02-25 11:12
Duplicate of #29

**Closed by fritzmg** 2020-02-25 11:12 UTC

**Comment by Cleanerrr** [comment] 2020-02-25 11:22
Hi,
thank you for your answer.
I believe you meant on this:
2. Hide the menu until the document is done loading.
`<style>
    #my-menu:not( .mm-menu ) {
        display: none;
    }
</style>`

**Comment by fritzmg** [comment] 2020-02-25 11:23
Yes :)

**Comment by Cleanerrr** [comment] 2020-02-25 11:24
Thank you very much :)
